name: Schedule Python Script

on:
  schedule:
    # Runs at 16:00 UTC every Monday to Friday
    - cron: '0 16 * * 1-5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests
          pip install gspread oauth2client
      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: python downloader.py
      - name: Upload block deals report
        uses: actions/upload-artifact@v2
        with:
          name: block-deals
          path: block_deals_*.csv
